name: Build Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Pnpm
        uses: pnpm/action-setup@v4

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.20.0
          cache: pnpm
      - name: Run build
        run: |
          node -v
          pnpm -v
          pnpm install
          pnpm run build
